name: Commit Stage

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Project + Cache Setup ------------------------------- #
      - name: Set up Python 3.12.1
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'
          cache: pip
          cache-dependency-path: './requirements.txt'

      - name: Install dependencies
        id: install-dependencies
        run: pip install -r requirements.txt

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Unit Tests ------------------------------- #
      - name: Install dependencies
        id: install-dependencies
        run: pip install -r requirements.txt

      - name: Unit Testing with pytest
        id: unit_test
        run: pytest app/tests/services/

  analyze:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Static Analysis ------------------------------- #
      - name: Install dependencies
        id: install-dependencies
        run: pip install -r requirements.txt

      - name: Lint and Format code
        id: lint
        run: pre-commit run --all-files
