name: Commit Stage

on:
  push:
    branches:
      - '*'
      - '!master'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commit_stage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Commit Stage ------------------------------- #
      - name: Commit Stage
        id: commit-stage
        uses: ./.github/actions/commit-stage-action
