name: Commit Stage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.0
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"
          cache: 'pip'

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Test with pytest
        id: test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest

  analyze:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Lint and Format code
        id: lint
        run: |
          pre-commit run --all-files
