name: Deploy Stage

on: [push]

#on:
#  workflow_run:
#    workflows:
#      - 'Commit Stage'
#    branches:
#      - main
#    types:
#      - completed


env:
  APP_NAME: hello-world
  APP_PORT: 80
  OPENSHIFT_NAMESPACE: davidher28-dev

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Application Versioning ------------------------------- #
      - name: Bump Application Version and Push Tag
        id: tagging
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # ------------------------------- Docker Build and Push ------------------------------- #
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}

      - name: Docker Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # ------------------------------- GitHub Release ------------------------------- #
      - name: Create a GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.tagging.outputs.new_tag }}
          tag: ${{ steps.tagging.outputs.new_tag }}

      # ------------------------------- Red Hat OpenShift Deployment ------------------------------- #
      - name: Log in to OpenShift
        id: oc_login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Create and expose app
        id: oc_deploy
        env:
          IMAGE_REPOSITORY: ${{ vars.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ steps.tagging.outputs.new_tag }}
        run: |
          export IMAGE="$IMAGE_REPOSITORY/fastapi:$IMAGE_TAG"
          export PORT=${{ env.APP_PORT }}

          export SELECTOR="app=${{ env.APP_NAME }}"
          echo "SELECTOR=$SELECTOR" >> $GITHUB_ENV

          set -x
          # Take down any old deployment
          oc delete all --selector="$SELECTOR"
          oc new-app --name $APP_NAME --image="$IMAGE"

          oc patch svc $APP_NAME -p "{ \"spec\": { \"ports\": [{ \"name\": \"$PORT-tcp\", \"port\": $PORT }] } }"
          oc expose service $APP_NAME --port=$PORT

          oc get all --selector="$SELECTOR"
          set +x

          export ROUTE="$(oc get route $APP_NAME -o jsonpath='{.spec.host}')"
          echo "$APP_NAME is exposed at $ROUTE"
          echo "ROUTE=$ROUTE" >> $GITHUB_ENV

      - name: View application route
        run: |
          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
          echo "======================== Your application is available at: ========================"
          echo ${{ env.ROUTE }}
          echo "==================================================================================="
          echo
          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
