name: Deploy Stage

on: [push]

#on:
#  workflow_run:
#    workflows:
#      - 'Commit Stage'
#    branches:
#      - main
#    types:
#      - completed


env:
  APP_NAME: hello-world
  APP_PORT: 8080
  OPENSHIFT_NAMESPACE: davidher28-dev

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Application Versioning ------------------------------- #
      - name: Bump Application Version and Push Tag
        id: tagging
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # ------------------------------- Docker Build and Push ------------------------------- #
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}

      - name: Docker Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # ------------------------------- GitHub Release ------------------------------- #
      - name: Create a GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.tagging.outputs.new_tag }}
          tag: ${{ steps.tagging.outputs.new_tag }}
          allowUpdates: true

      # ------------------------------- Red Hat OpenShift Deployment ------------------------------- #
      - name: Log in to OpenShift
        id: oc_login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Create and expose app
        id: deploy-and-expose
        uses: redhat-actions/oc-new-app@v1
        env:
          IMAGE_REPOSITORY: ${{ vars.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ steps.tagging.outputs.new_tag }}
        with:
          app_name: ${{ env.APP_NAME }}
          image: docker.io/${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          port: ${{ env.APP_PORT }}

      - name: View application route
        env:
          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
        run: |
          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
          echo "======================== Your application is available at: ========================"
          echo ${{ env.ROUTE }}
          echo "==================================================================================="
          echo
          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
