name: Deploy Stage

on: [push]

#on:
#  workflow_run:
#    workflows:
#      - 'Commit Stage'
#    branches:
#      - main
#    types:
#      - completed

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Application Versioning ------------------------------- #
      - name: Bump Application Version and Push Tag
        id: tagging
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # ------------------------------- Docker Build and Push ------------------------------- #
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}

      - name: Docker Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # ------------------------------- GitHub Release ------------------------------- #
      - name: Create a GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.tagging.outputs.new_tag }}
          tag: ${{ steps.tagging.outputs.new_tag }}

      # ------------------------------- Red Hat OpenShift Deployment ------------------------------- #
      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Create and expose app
        env:
          IMAGE_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ steps.tagging.outputs.new_tag }}
        run: |
          sed -i "s|$DOCKER_IMAGE|$IMAGE_REPOSITORY/fastapi:$IMAGE_TAG|g" ./kubernetes/deployment.yaml && \
          oc create -f ./kubernetes/deployment.yaml
          oc apply -f ./kubernetes/service.yaml
