name: Deploy Stage
run-name: Deploy Stage - ${{ github.ref }}

on:
  push:
    branches:
      - main

env:
  APP_NAME: hello-world
  APP_PORT: 8080
  OPENSHIFT_NAMESPACE: davidher28-dev

jobs:
  # ------------------------------- Commit Stage ------------------------------- #
  commit_stage:
    name: Commit Stage
    uses: ./.github/workflows/commit-stage.yaml

  # ------------------------------- Integration Tests ------------------------------- #
  integration_test:
    runs-on: ubuntu-22.04
    needs: commit_stage
    name: Integration Test
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache from the build stage
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install cached dependencies
        id: restore-dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Integration Testing with pytest
        run: pytest app/tests/integration/

  # ------------------------------- Container Versioning ------------------------------- #
  publish:
    runs-on: ubuntu-22.04
    needs: integration_test
    name: Publish Container
    outputs:
      old_tag: ${{ steps.tagging.outputs.tag }}
      new_tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump Application Version and Push Tag
        id: tagging
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ steps.tagging.outputs.new_tag }}

      - name: Docker Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # ------------------------------- Red Hat OpenShift Green Deployment ------------------------------- #
  blue-deployment:
    runs-on: ubuntu-22.04
    needs: publish
    name: Deploy Blue Container
    outputs:
      route: ${{ steps.deploy-and-expose.outputs.route }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to OpenShift
        id: oc_login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Deploy and expose app
        id: deploy-and-expose
        run: |
          oc new-app --name=${{ env.APP_NAME }}-blue docker.io/${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ needs.publish.outputs.old_tag }} -n ${{ env.OPENSHIFT_NAMESPACE }}

          export SELECTOR="app=${{ env.APP_NAME }}"
          echo "SELECTOR=$SELECTOR" >> $GITHUB_OUTPUT

  green-deployment:
    runs-on: ubuntu-22.04
    needs: publish
    name: Deploy Green Container
    outputs:
      route: ${{ steps.deploy-and-expose.outputs.route }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to OpenShift
        id: oc_login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Deploy and expose app
        id: deploy-and-expose
        run: |
          oc new-app --name=${{ env.APP_NAME }}-green docker.io/${{ vars.DOCKERHUB_USERNAME }}/fastapi:${{ needs.publish.outputs.new_tag }} -n ${{ env.OPENSHIFT_NAMESPACE }}
          oc expose svc/${{ env.APP_NAME }} --port=${{ env.APP_PORT }} -n ${{ env.OPENSHIFT_NAMESPACE }}

          export SELECTOR="app=${{ env.APP_NAME }}"
          echo "SELECTOR=$SELECTOR" >> $GITHUB_OUTPUT

          export ROUTE=$(oc get route -n ${{ env.OPENSHIFT_NAMESPACE }} -l $SELECTOR -o jsonpath='{.items[0].spec.host}')
          echo "ROUTE=$ROUTE" >> $GITHUB_OUTPUT

      - name: View application route
        id: view_application_route
        env:
          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
        run: |
          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
          echo "======================== The application is available at: ========================"
          echo ${{ env.ROUTE }}
          echo "==================================================================================="
          echo
          echo "It can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""

  deployment_test:
    runs-on: ubuntu-22.04
    needs: green-deployment
    name: Deployment Test
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Deployment Test ------------------------------- #
      - name: Test application deployment
        id: test_deploy
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 3
          retry_wait_seconds: 10
          max_attempts: 30
          warning_on_retry: false
          command: curl -sSfL ${{ needs.deployment.outputs.route }}
