name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.1

      - name: Set up Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
        run: pytest

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
